# Generated by Django 3.2.9 on 2021-12-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211202_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='americancrew',
            name='mini_description',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='philipmartins',
            name='mini_description',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
    ]
