# Generated by Django 3.2.9 on 2021-12-03 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211202_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cart', verbose_name='Корзина'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('payment_delivery', 'Наложенный платеж'), ('full_payment', 'Полная предоплата')], default='payment_delivery', max_length=100, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='americancrew',
            name='mini_description',
            field=models.TextField(max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='philipmartins',
            name='mini_description',
            field=models.TextField(max_length=255, null=True, verbose_name='Краткое описание'),
        ),
    ]
